# Generated by Django 4.2.3 on 2023-07-29 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(verbose_name='Fecha de eliminación')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=25, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Maintenance type',
                'verbose_name_plural': 'Maintenance types',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(verbose_name='Fecha de eliminación')),
                ('description', models.CharField(max_length=25, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('feedback', models.CharField(blank=True, max_length=30, null=True, verbose_name='Feedback')),
                ('cancel_note', models.CharField(blank=True, max_length=35, null=True, verbose_name='Cancel note')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance request',
                'verbose_name_plural': 'Maintenance requests',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(verbose_name='Fecha de eliminación')),
                ('description', models.CharField(max_length=25, verbose_name='Description')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance report',
                'verbose_name_plural': 'Maintenance reports',
            },
        ),
    ]
