# Generated by Django 4.2.3 on 2023-07-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
