# Generated by Django 4.2.3 on 2023-07-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancereport_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
