# Generated by Django 4.2.3 on 2023-07-31 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.area')),
            ],
            options={
                'verbose_name': 'Subarea',
                'verbose_name_plural': 'Subareas',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
