# Generated by Django 4.2.3 on 2023-07-29 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.area')),
            ],
            options={
                'verbose_name': 'Subarea',
                'verbose_name_plural': 'Subareas',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.location')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
